[log]
log_level = "debug"

[grpc_server]
addr = ":8081"

[app]
repo_type = "psql"

[psql]
dsn = "host=localhost port=5432 user=vdudov password=123qwe dbname=calendar sslmode=disable"

[ratelimits]
login = 10
password = 100
ip = 1000
duration = 60
